### ISSUE TITLE
Bug This!

### ISSUE THREAD

**Issue by menz0050** [5AWTANGUS/TAFESA-5AWT-Course-Playground#4]
This is my Comment

**Comment by 5AWTANGUS** [comment]
This is my comment!

**Comment by 5AWTANGUS** [comment]
#2 added <required> to all fields

**Comment by 5AWTANGUS** [comment]
#2
[file1.txt](https://github.com/5AWTANGUS/TAFESA-5AWT-Course-Playground/files/317838/file1.txt)

**Comment by 5AWTANGUS** [comment]
#2 - fixed required fields in signup
